"git":
  "depth": !!bool >-
    false
"language": >-
  minimal
"matrix":
  "include":
  - "before_cache":
    - >-
      echo "pushing these paths to cachix:"
    - >-
      cat $HOME/push-to-cachix
    - >
      if [ -n "$CACHIX_SIGNING_KEY" ]; then
        cachix push lorri-test < $HOME/push-to-cachix
      fi
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/liblorri.rlib"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/lorri*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/build/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/liblorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/.fingerprint/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/build_script_build-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/direnv-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/direnv-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/direnv-*"
    "cache":
      "directories":
      - >-
        $HOME/.cargo
      - >-
        $TRAVIS_BUILD_DIR/target
    "env":
    - >-
      CACHE_NAME=linux
    "install":
    - >-
      nix-env -iA cachix -f https://cachix.org/api/v1/install
    - >-
      cachix use lorri-test
    "language": >-
      nix
    "name": >-
      cargo build & linters
    "nix": >-
      2.3.1
    "os": >-
      linux
    "script":
    - >-
      set -e
    - >
      export LC_ALL=C.UTF-8

      export LC_CTYPE=C.UTF-8

      export LANG=C.UTF-8

      export LANGUAGE=C.UTF-8
    - >-
      cat $(nix-build --quiet ./.travis.yml.nix --no-out-link) > .travis.yml
    - >-
      git diff -q ./.travis.yml
    - >
      testsuite=$(nix-build --arg isDevelopmentShell false -A ci.testsuite shell.nix)

      eval "$testsuite"
    - >-
      printf '%s' "$testsuite" >> $HOME/push-to-cachix
  - "before_cache":
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/liblorri.rlib"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/lorri*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/build/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/liblorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/.fingerprint/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/build_script_build-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/direnv-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/direnv-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/direnv-*"
    "before_install":
    - >
      wget --retry-connrefused --waitretry=1 -O /tmp/nix-install https://nixos.org/releases/nix/nix-2.3.1/install

      yes | sh /tmp/nix-install --daemon

      if [ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
        source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      elif [ -f ${TRAVIS_HOME}/.nix-profile/etc/profile.d/nix.sh ]; then
        source source ${TRAVIS_HOME}/.nix-profile/etc/profile.d/nix.sh
      fi
    "cache":
      "directories":
      - >-
        $HOME/.cargo
      - >-
        $TRAVIS_BUILD_DIR/target
    "env":
    - >-
      CACHE_NAME=macos
    "name": >-
      cargo build & linters
    "os": >-
      osx
    "script":
    - >-
      set -e
    - >
      export LC_ALL=C.UTF-8

      export LC_CTYPE=C.UTF-8

      export LANG=C.UTF-8

      export LANGUAGE=C.UTF-8
    - >-
      cat $(nix-build --quiet ./.travis.yml.nix --no-out-link) > .travis.yml
    - >-
      git diff -q ./.travis.yml
    - >
      testsuite=$(nix-build --arg isDevelopmentShell false -A ci.testsuite shell.nix)

      eval "$testsuite"
    - >-
      printf '%s' "$testsuite" >> $HOME/push-to-cachix
  - "before_cache":
    - >-
      echo "pushing these paths to cachix:"
    - >-
      cat $HOME/push-to-cachix
    - >
      if [ -n "$CACHIX_SIGNING_KEY" ]; then
        cachix push lorri-test < $HOME/push-to-cachix
      fi
    "install":
    - >-
      nix-env -iA cachix -f https://cachix.org/api/v1/install
    - >-
      cachix use lorri-test
    "language": >-
      nix
    "name": >-
      nix-build
    "nix": >-
      2.3.1
    "os": >-
      linux
    "script":
    - >-
      set -e
    - >-
      nix-build
    - >-
      nix-env -i ./result
    - >-
      lorri self-upgrade local $(pwd)
    - >-
      readlink ./result >> $HOME/push-to-cachix
  - "before_install":
    - >
      wget --retry-connrefused --waitretry=1 -O /tmp/nix-install https://nixos.org/releases/nix/nix-2.3.1/install

      yes | sh /tmp/nix-install --daemon

      if [ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
        source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      elif [ -f ${TRAVIS_HOME}/.nix-profile/etc/profile.d/nix.sh ]; then
        source source ${TRAVIS_HOME}/.nix-profile/etc/profile.d/nix.sh
      fi
    "name": >-
      nix-build
    "os": >-
      osx
    "script":
    - >-
      set -e
    - >-
      nix-build
    - >-
      nix-env -i ./result
    - >-
      lorri self-upgrade local $(pwd)
    - >-
      readlink ./result >> $HOME/push-to-cachix
